{
 "title": "PADO Network Metrics",
 "description": "PADO Network Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "AvsName", "label": "AVS Name", "query": { "query": "label_values(avs_name)" } }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVS Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eigen_performance_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Average response time per method.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(eigen_rpc_request_duration_seconds_sum{method=~\".*\", avs_name=\"$AvsName\"}[$__rate_interval]) / rate(eigen_rpc_request_duration_seconds_count{method=~\".*\", avs_name=\"$AvsName\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Balance Total",
   "type": "stat",
   "description": "The total balance per token.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eigen_balance_total", "legendFormat": "${{token}}" }
   ]
  },
  { "title": "Task-DataSharing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Failed Count",
   "type": "stat",
   "description": "Number of failures related to task type.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigen_task_failed_count{task_type=\"EL.DataSharing\"}",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "description": "Success rate between 0 and 100.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*eigen_task_success_count{task_type=\"EL.DataSharing\"}/(eigen_task_failed_count{task_type=\"EL.DataSharing\"}+eigen_task_success_count{task_type=\"EL.DataSharing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Count",
   "type": "stat",
   "description": "Number of successes related to task type.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigen_task_success_count{task_type=\"EL.DataSharing\"}",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Registered Stakes",
   "type": "stat",
   "description": "Operator stake in <quorum> of StakeRegistry contract",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quorum_number) (eigen_registered_stakes{avs_name=\"$AvsName\"}) / 1000000000000000000",
     "legendFormat": "#{{quorum_number}}"
    }
   ]
  }
 ]
}